spring:
  datasource:
    url: jdbc:mysql://116.62.60.135:3306/ysl?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: K&i.edR.h55K  #数据库名、用户名和密码改为自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1347999420@qq.com
    password: izqahuqnjlmzgcec
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  redis:
    host: 116.62.60.135
    port: 6379
    timeout: 10000   #客户端超时
    password: Shun134!
    database: 1
#    lettuce:
#      pool:
#        max-active:5   #最大连接数
#        min-idle:0   #最小空闲
#        max-wait:-1   #连接超时
#        max-idle:-1  #最大空闲
elasticsearch:
  host: 116.62.60.135
  port: 9200
